version: '3'

services:
  client:
    image: chord
    build: .
    container_name: client
    command: python3 client.py
    depends_on: [ node_2, node_7, node_11, node_17, node_22, node_27 ]

  node_2:
    image: chord
    build: .
    container_name: node_2
    command: sh -c 'python3 node*.py 2'

  node_7:
    image: chord
    build: .
    container_name: node_7
    command: sh -c 'python3 node*.py 7'

  node_11:
    image: chord
    build: .
    container_name: node_11
    command: sh -c 'python3 node*.py 11'

  node_17:
    image: chord
    build: .
    container_name: node_17
    command: sh -c 'python3 node*.py 17'

  node_22:
    image: chord
    build: .
    container_name: node_22
    command: sh -c 'python3 node*.py 22'

  node_27:
    image: chord
    build: .
    container_name: node_27
    command: sh -c 'python3 node*.py 27'
